# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1CG7_QXZavymf7SFN7XQhHkuj2TEz15_9
"""

x = bool(100)

#Menampilkan x:
print(x)

#Menampilkan data type x:
print(type(x))

x = str("Belajar Phyton yuk")

#Menampilkan x:
print(x)

#Menampilkan data type x:
print(type(x))

x = int(15)

#Menampilkan x:
print(x)

#Menampilkan data type x:
print(type(x))

x = float(20.5)

#Menampilkan x:
print(x)

#Menampilkan data type x:
print(type(x))

x = 1j

#Menampilkan x:
print(x)

#Menampilkan data type x:
print(type(x))

x = ["apple", "banana", "cherry"]

#Menampilkan x:
print(x)

#Menampilkan data type x:
print(type(x))

x = ("apple", "banana", "cherry")

#Menampilkan x:
print(x)

#Menampilkan data type x:
print(type(x))

x = {"name" : "John", "age" : 36}

#Menampilkan x:
print(x)

#Menampilkan data type x:
print(type(x))

x = '9A'

#Menampilkan x:
print(x)

#Menampilkan data type x:
print(type(x))

x = b"Hello"

#Menampilkan x:
print(x)

#Menampilkan data type x:
print(type(x))